import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';

const markup = await readFile(new URL('../dapp/index.html', import.meta.url), 'utf8');
const earn = markup.match(/<section[^>]*id="earn"[^>]*>[\s\S]*?<\/section>/)?.[0] || '';
const v3Workspace = await readFile(new URL('../dapp/v3-workspace.js', import.meta.url), 'utf8');
const earnTransactions = await readFile(new URL('../dapp/earn-transactions.js', import.meta.url), 'utf8');
const v3ZapTransactions = await readFile(new URL('../dapp/earn-v3-zap.js', import.meta.url), 'utf8');

assert.ok(earn, 'Earn section must remain present.');
assert.match(earn, /id="earnRoutesTab"/);
assert.match(earn, /id="earnPositionsTab"/);
assert.match(earn, /Verified SUI \/ TREE farm/);
assert.match(earn, /id="earnV2ZapOpen"/);
assert.match(earn, /id="earnV2ZapPanel"/);
assert.match(earn, /id="earnZapAction"/);
assert.match(earn, /Wallet approvals[\s\S]*2 · Zap, then stake/);
assert.match(earn, /Zap &amp; Stake/);
assert.match(earn, /id="earnClaimVictory"/);
assert.match(earn, /Claim VICTORY Rewards/);
assert.match(earn, /id="earnClaimStatus"/);
assert.match(earn, /id="earnV2PositionSui"/);
assert.match(earn, /id="earnV2PositionTree"/);
assert.match(earn, /id="earnV2ClaimableVictory"/);
assert.match(earn, /id="earnV2PositionLink"/);
assert.doesNotMatch(earn, /id="earnV3ZapOpen"/);
assert.doesNotMatch(earn, /Manage V3/);
assert.match(v3Workspace, /data-v3-tab="zap"/);
assert.match(v3Workspace, /id="earnV3ZapOpen"/);
assert.match(v3Workspace, /id="earnV3ZapPanel"/);
assert.match(v3Workspace, /id="earnV3ZapAction"/);
assert.match(v3Workspace, /Wallet approvals[\s\S]*1 · Position \+ incentives/);
assert.match(v3Workspace, /data-v3-go-positions/);
assert.match(v3Workspace, /tree:v3-workspace-ready/);
assert.doesNotMatch(earn, /https:\/\/dex\.suidex\.org/);
assert.equal((earn.match(/target="_blank" rel="noopener noreferrer"/g) || []).length, 1, 'Only the live V2 position object may open an external explorer.');
assert.match(earn, /second wallet approval/i);
assert.match(v3Workspace, /explicit wallet approval/i);
assert.match(earnTransactions, /'tree-token\.xyz', 'www\.tree-token\.xyz'/);
assert.match(earnTransactions, /buildV2ClaimRewardsTransaction/);
assert.match(earnTransactions, /extractPositiveV2VictoryReward/);
assert.match(earnTransactions, /No verified VICTORY rewards are claimable right now/);
assert.match(earnTransactions, /VICTORY rewards were claimed successfully/);
assert.match(earnTransactions, /getV2FarmPosition/);
assert.match(earnTransactions, /estimateV2PositionUnderlying/);
assert.match(earnTransactions, /loadV2Position/);
assert.doesNotMatch(earnTransactions, /Preview execution only/);
assert.match(v3ZapTransactions, /isTreeV3ExecutionHost\(location\.hostname\)/);
assert.match(v3ZapTransactions, /tree:v3-workspace-ready/);
assert.doesNotMatch(v3ZapTransactions, /Preview execution only/);

console.log('Earn routes source: PASS (native V2 farm only; V3 zap and management live in V3)');
