import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
const markup = await readFile('dapp/index.html', 'utf8');
const app = await readFile('dapp/app.js', 'utf8');
const swap = await readFile('dapp/swap-router.js', 'utf8');
const quote = await readFile('netlify/functions/tree-swap-quote.ts', 'utf8');
assert.equal(app.includes('const DAPP_SWAP_EXECUTION_ENABLED = false'), true);
assert.equal(app.includes("document.getElementById('swapSui')"), false);
assert.equal(markup.includes('swap-router.js'), true);
assert.equal(markup.includes('swap-router.css'), true);
assert.equal(markup.includes('Best available TREE route'), true);
assert.equal(markup.includes('Display estimate only'), false);
assert.equal(swap.includes('const TREE_DECIMALS = 6'), true);
assert.equal(swap.includes('const SUI_DECIMALS = 9'), true);
assert.equal(swap.includes("text.startsWith('.') ? `0${text}` : text"), true);
assert.equal(swap.includes('client.core.simulateTransaction'), true);
assert.equal(swap.includes('client.core.waitForTransaction'), true);
assert.equal(swap.includes("/^deploy-preview-\\d+--tree-token\\.netlify\\.app$/i"), true);
assert.equal(swap.includes("location.hostname === 'tree-token.xyz'"), false);
assert.equal(swap.includes('MAX_EXECUTABLE_PRICE_IMPACT = 5'), true);
assert.equal(swap.includes('ALLOWED_MOVE_PACKAGES'), true);
assert.equal(swap.includes('selected[0].objectId'), true);
assert.equal(swap.includes('coin.objectId'), true);
assert.equal(swap.includes('coinObjectId'), false);
assert.equal(swap.includes('swap_exact_tokens1_for_tokens0'), true);
assert.equal(swap.includes("swap_exact_tokens1_for_token0'"), false);
assert.equal(swap.includes("throw new Error('Unsupported coin type in route metadata.')"), true);
assert.equal(quote.includes("path: '/api/tree-swap-quote'"), true);
assert.equal(swap.includes('@mysten/sui@2.23.1/grpc'), true);
assert.equal(swap.includes('SuiGrpcClient'), true);
assert.equal(swap.includes('@mysten/sui@1.43.0'), false);
assert.equal(swap.includes('dryRunTransactionBlock'), false);
assert.equal(swap.includes('waitForTransactionBlock'), false);
console.log('TREE swap client safeguards: PASS (best-route quote, 9/6 decimals, simulation, finality, preview-only execution, package allowlist)');
