import { test } from 'node:test';
import assert from 'node:assert/strict';
import { createInlineAccountHandler } from '../netlify/lib/tree-account-inline.mjs';
import { createAccountService, COOKIE, FLOW_COOKIE, digest } from '../netlify/lib/tree-account-core.mjs';
const origin='https://deploy-preview-18--tree-token.netlify.app', gameOrigin='https://deploy-preview-1--treeforce89.netlify.app';
const wallet={family:'sui',address:'0x1',chainId:'sui:mainnet'};
const cookie=(r,n)=>r.headers.getSetCookie().find(c=>c.startsWith(n+'='))?.split(';')[0]||'';
function fixture(){
 const values=new Map();let version=0,clock=2000000000000;const proofs=[];
 const store={async get(k){return structuredClone(values.get(k)?.data||null)},async getWithMetadata(k){return structuredClone(values.get(k)||null)},async setJSON(k,data,o={}){const old=values.get(k);if(o.onlyIfNew&&old||o.onlyIfMatch&&old?.etag!==o.onlyIfMatch)return {modified:false};values.set(k,{data:structuredClone(data),etag:String(++version)});return {modified:true}},async delete(k){values.delete(k)}};
 const settings={store,origin,gameOrigin,now:()=>clock,evmMessage:p=>`SIGN IN ${p.origin} ${p.wallet.address} ${p.nonce}`,verifySignature:async(p,s)=>{proofs.push(p);return s==='valid'?(p.wallet.family==='sui'?'sui':'eoa'):null}};
 const handler=createInlineAccountHandler(settings),legacy=createAccountService(settings);
 const request=(body,headers={})=>new Request(origin+'/api/tree-account-inline',{method:'POST',headers:{'Content-Type':'application/json',...headers},body:JSON.stringify({clientOrigin:gameOrigin,...body})});
 const post=(body,headers)=>handler(request(body,headers),{ip:'fixture'});
 async function challenge(w=wallet){const r=await post({action:'challenge',...w});assert.equal(r.status,200);return r.json()}
 const verify=p=>post({action:'verify',nonce:p.nonce,binding:p.binding,signature:'valid'});
 const core=(body,headers={})=>legacy(new Request(origin+'/api/tree-account',{method:'POST',headers:{'Content-Type':'application/json',...headers},body:JSON.stringify(body)}),{ip:'legacy'});
 return {values,store,proofs,handler,post,challenge,verify,core,advance:n=>clock+=n};
}
test('inline challenge binds signature domain to game and supplies a server-only proof binding',async()=>{const f=fixture(),p=await f.challenge();assert.match(p.message,/Domain: deploy-preview-1--treeforce89.netlify.app/);assert.equal(p.binding.length,64);assert.equal(f.values.get('challenges/'+digest(p.nonce)).data.origin,gameOrigin)});
test('new inline child works with the unchanged central game-session validator',async()=>{const f=fixture(),p=await(await f.verify(await f.challenge())).json();assert.equal(p.status,'ok');const r=await f.core({action:'game-session',token:p.accessToken});assert.equal((await r.json()).identity.accountId,p.identity.accountId);assert.equal(p.identity.entitlement,'not-checked')});
test('legacy popup and inline login resolve the SAME existing account UUID',async()=>{const f=fixture(),c=await f.core({action:'challenge',...wallet},{Origin:origin}),p=await c.json();const v=await f.core({action:'verify',nonce:p.nonce,signature:'valid'},{Origin:origin,Cookie:cookie(c,FLOW_COOKIE)});const old=(await v.json()).identity;const fresh=await(await f.verify(await f.challenge())).json();assert.equal(fresh.identity.accountId,old.accountId);assert.equal([...f.values.keys()].filter(k=>k.startsWith('aliases/')).length,1)});
test('EVM-only uses the same EOA account on both supported testnets',async()=>{const f=fixture(),w={family:'evm',address:'0x'+'2'.repeat(40),chainId:97};const a=await(await f.verify(await f.challenge(w))).json(),b=await(await f.verify(await f.challenge({...w,chainId:46630}))).json();assert.equal(a.identity.accountId,b.identity.accountId)});
test('no wallet merge: different signatures/wallets create separate identities',async()=>{const f=fixture(),a=await(await f.verify(await f.challenge())).json(),b=await(await f.verify(await f.challenge({...wallet,address:'0x2'}))).json();assert.notEqual(a.identity.accountId,b.identity.accountId)});
test('invalid signature consumes nonce and creates no session',async()=>{const f=fixture(),p=await f.challenge(),b={action:'verify',nonce:p.nonce,binding:p.binding,signature:'bad'};assert.equal((await f.post(b)).status,401);assert.equal((await f.verify(p)).status,401);assert.equal([...f.values.keys()].filter(k=>k.startsWith('game-sessions/')).length,0)});
test('wrong browser binding fails before signature verification',async()=>{const f=fixture(),p=await f.challenge();assert.equal((await f.post({action:'verify',nonce:p.nonce,binding:'f'.repeat(64),signature:'valid'})).status,401);assert.equal(f.proofs.length,0)});
test('cancel invalidates a pending wallet signature, without logging out an existing session',async()=>{const f=fixture(),signed=await(await f.verify(await f.challenge())).json(),p=await f.challenge();assert.equal((await f.post({action:'cancel',nonce:p.nonce,binding:p.binding})).status,200);assert.equal((await f.verify(p)).status,401);assert.equal((await f.core({action:'game-session',token:signed.accessToken})).status,200)});
test('expired and concurrent duplicate signatures cannot create multiple authenticated sessions',async()=>{const f=fixture(),p=await f.challenge();const results=await Promise.all([f.verify(p),f.verify(p)]);assert.deepEqual(results.map(r=>r.status).sort(),[200,401]);const q=await f.challenge();f.advance(300001);assert.equal((await f.verify(q)).status,401)});
test('browser channel and unexpected game origin are blocked',async()=>{const f=fixture();assert.equal((await f.post({action:'challenge',...wallet},{Origin:gameOrigin})).status,403);assert.equal((await f.post({action:'challenge',...wallet},{'sec-fetch-site':'cross-site'})).status,403);assert.equal((await f.post({action:'challenge',...wallet,clientOrigin:'https://evil.example'})).status,403)});
test('caller cannot substitute account ID, message, or billing fields',async()=>{const f=fixture();for(const extra of [{accountId:'forged'},{message:'evil'},{amount:1100},{token:'a'.repeat(64)}])assert.equal((await f.post({action:'challenge',...wallet,...extra})).status,400)});
test('legacy central-origin challenge cannot be verified through inline route',async()=>{const f=fixture(),c=await f.core({action:'challenge',...wallet},{Origin:origin}),p=await c.json(),binding=cookie(c,FLOW_COOKIE).split('=')[1];assert.equal((await f.verify({...p,binding})).status,401)});
test('inline login never writes credits, scores, entitlements or wallet links',async()=>{const f=fixture();await f.verify(await f.challenge());assert.ok([...f.values.keys()].every(k=>/^(limits|challenges|aliases|sessions|game-sessions|grants)\//.test(k)))});
test('response is uncached and parent revocation still invalidates child',async()=>{const f=fixture(),r=await f.verify(await f.challenge()),p=await r.json();assert.match(r.headers.get('cache-control'),/no-store/);const child=f.values.get('game-sessions/'+digest(p.accessToken)).data;await f.store.delete(child.parentKey);assert.equal((await f.core({action:'game-session',token:p.accessToken})).status,401)});
