import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';

const source = readFileSync(new URL('../dapp/v3-transactions.js', import.meta.url), 'utf8');
const core = readFileSync(new URL('../dapp/v3-transaction-core.js', import.meta.url), 'utf8');
assert.match(source, /PREVIEW_HOST_PATTERN/);
assert.match(source, /Native V3 position execution is disabled on production/);
assert.match(source, /Preview transaction review/);
assert.match(source, /Nothing is signed or submitted until you approve/);
assert.match(source, /validAddress\(window\.playerAddress\)/);
assert.match(source, /classList\.remove\('v3-disabled-action', 'secondary'\)/);
assert.match(source, /classList\.add\('button', 'primary'\)/);
assert.match(source, /preliminarySimulation/);
assert.match(source, /finalSimulation/);
assert.ok(source.indexOf('finalSimulation') < source.indexOf('signAndExecute(finalTx)'));
assert.match(source, /buildIncreaseTreeV3Position/);
assert.match(source, /extractAddLiquidityEvent\(preliminarySimulation, positionId\)/);
assert.match(source, /This verified position is not owned by the connected wallet/);
assert.match(source, /increaseConfirmText/);
assert.match(source, /window\.confirm/);
assert.match(source, /waitForFinality/);
assert.doesNotMatch(source, /finalized\?\.effects &&/);
assert.match(core, /::liquidity::open_position/);
assert.match(core, /::liquidity::add_liquidity/);
assert.match(core, /assertAllowedV3Transaction/);
assert.match(core, /assertAllowedIncreaseV3Transaction/);
assert.match(core, /buildIncreaseTreeV3Position/);
assert.doesNotMatch(core, /::liquidity::remove_liquidity/);
assert.doesNotMatch(core, /::collect::/);
console.log('V3 transaction source safeguards passed.');
