import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';

const source = readFileSync(new URL('../dapp/v3-transactions.js', import.meta.url), 'utf8');
const core = readFileSync(new URL('../dapp/v3-transaction-core.js', import.meta.url), 'utf8');
assert.match(source, /PREVIEW_HOST_PATTERN/);
assert.match(source, /Native V3 position execution is disabled on production/);
assert.match(source, /Preview transaction review/);
assert.match(source, /Nothing is signed or submitted until you approve/);
assert.match(source, /validAddress\(window\.playerAddress\)/);
assert.match(source, /classList\.remove\('v3-disabled-action', 'secondary'\)/);
assert.match(source, /classList\.add\('button', 'primary'\)/);
assert.match(source, /preliminarySimulation/);
assert.match(source, /finalSimulation/);
assert.ok(source.indexOf('finalSimulation') < source.indexOf('signAndExecute(finalTx)'));
assert.match(source, /buildIncreaseTreeV3Position/);
assert.match(source, /extractAddLiquidityEvent\(preliminarySimulation, positionId\)/);
assert.match(source, /This verified position is not owned by the connected wallet/);
assert.match(source, /increaseConfirmText/);
assert.match(source, /buildRemoveTreeV3Position/);
assert.match(source, /extractRemoveLiquidityEvent\(preliminarySimulation, positionId\)/);
assert.match(source, /removeConfirmText/);
assert.match(source, /Removing 100% does not close the position object/);
assert.match(source, /buildCollectTreeV3Fees/);
assert.match(source, /extractFeeCollectedEvent\(preliminarySimulation, positionId\)/);
assert.match(source, /No collectible SUI or TREE fees are available right now/);
assert.match(source, /feeConfirmText/);
assert.match(source, /buildCollectTreeV3Rewards/);
assert.match(source, /extractRewardCollectedEvents\(preliminarySimulation, positionId\)/);
assert.match(source, /positiveRewards/);
assert.match(source, /No verified VICTORY, TREE, or wBTC rewards are claimable right now/);
assert.match(source, /rewardConfirmText/);
assert.match(source, /window\.confirm/);
assert.match(source, /waitForFinality/);
assert.doesNotMatch(source, /finalized\?\.effects &&/);
assert.match(core, /::liquidity::open_position/);
assert.match(core, /::liquidity::add_liquidity/);
assert.match(core, /assertAllowedV3Transaction/);
assert.match(core, /assertAllowedIncreaseV3Transaction/);
assert.match(core, /buildIncreaseTreeV3Position/);
assert.match(core, /::liquidity::remove_liquidity/);
assert.match(core, /assertAllowedRemoveV3Transaction/);
assert.match(core, /buildRemoveTreeV3Position/);
assert.match(core, /::collect::fee/);
assert.match(core, /assertAllowedCollectFeeV3Transaction/);
assert.match(core, /buildCollectTreeV3Fees/);
assert.match(core, /::collect::reward/);
assert.match(core, /assertAllowedCollectRewardV3Transaction/);
assert.match(core, /buildCollectTreeV3Rewards/);
console.log('V3 transaction source safeguards passed.');
