import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';

const source = readFileSync(new URL('../dapp/v3-transactions.js', import.meta.url), 'utf8');
const core = readFileSync(new URL('../dapp/v3-transaction-core.js', import.meta.url), 'utf8');
assert.match(source, /isTreeV3ExecutionHost/);
assert.match(source, /Mainnet transactions live/);
assert.match(source, /Native V3 position execution is unavailable on this host/);
assert.match(source, /Preview transaction review/);
assert.match(source, /Nothing is signed or submitted until you approve/);
assert.match(source, /validAddress\(window\.playerAddress\)/);
assert.match(source, /classList\.remove\('v3-disabled-action', 'secondary'\)/);
assert.match(source, /classList\.add\('button', 'primary'\)/);
assert.match(source, /preliminarySimulation/);
assert.match(source, /finalSimulation/);
assert.ok(source.indexOf('finalSimulation') < source.indexOf('signAndExecute(finalTx)'));
assert.match(source, /buildIncreaseTreeV3Position/);
assert.match(source, /extractAddLiquidityEvent\(preliminarySimulation, positionId\)/);
assert.match(source, /This verified position is not owned by the connected wallet/);
assert.match(source, /increaseConfirmText/);
assert.match(source, /buildRemoveTreeV3Position/);
assert.match(source, /extractRemoveLiquidityEvent\(preliminarySimulation, positionId\)/);
assert.match(source, /removeConfirmText/);
assert.match(source, /buildWithdrawAllAndCloseTreeV3Position/);
assert.match(source, /exitConfirmText/);
assert.match(source, /positionDeleted\(preliminarySimulation, positionId\)/);
assert.match(source, /All assets claimed and withdrawn; position closed successfully/);
assert.match(source, /buildClaimAllTreeV3Position/);
assert.match(source, /extractFeeCollectedEvent\(preliminarySimulation, positionId\)/);
assert.match(source, /extractRewardCollectedEvents\(preliminarySimulation, positionId\)/);
assert.match(source, /positiveRewards/);
assert.match(source, /No fees or verified rewards are claimable right now/);
assert.match(source, /claimAllConfirmText/);
assert.match(source, /No wallet request was made/);
assert.match(source, /togglePositionManagementPanel/);
assert.match(source, /POSITION_MANAGEMENT_PANEL_SELECTOR/);
assert.match(source, /setAttribute\('aria-expanded', 'false'\)/);
assert.doesNotMatch(source, /Cancel (Increase|Remove|Fees|Rewards|Close)/);
assert.match(source, /confirmTransaction/);
assert.doesNotMatch(source, /window\.confirm/);
assert.match(source, /waitForFinality/);
assert.doesNotMatch(source, /finalized\?\.effects &&/);
assert.match(core, /::liquidity::open_position/);
assert.match(core, /::liquidity::add_liquidity/);
assert.match(core, /assertAllowedV3Transaction/);
assert.match(core, /assertAllowedIncreaseV3Transaction/);
assert.match(core, /buildIncreaseTreeV3Position/);
assert.match(core, /::liquidity::remove_liquidity/);
assert.match(core, /assertAllowedRemoveV3Transaction/);
assert.match(core, /buildRemoveTreeV3Position/);
assert.match(core, /::collect::fee/);
assert.match(core, /assertAllowedCollectFeeV3Transaction/);
assert.match(core, /buildCollectTreeV3Fees/);
assert.match(core, /::collect::reward/);
assert.match(core, /assertAllowedCollectRewardV3Transaction/);
assert.match(core, /buildCollectTreeV3Rewards/);
assert.match(core, /assertAllowedClaimAllV3Transaction/);
assert.match(core, /buildClaimAllTreeV3Position/);
assert.match(core, /assertAllowedWithdrawAllAndCloseV3Transaction/);
assert.match(core, /buildWithdrawAllAndCloseTreeV3Position/);
assert.match(core, /::liquidity::close_position/);
assert.match(core, /assertAllowedCloseV3Transaction/);
assert.match(core, /buildCloseTreeV3Position/);
console.log('V3 transaction source safeguards passed.');
