import {test} from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {encodeCheckpoint,createFlightStorage,canonicalSnapshot} from '../flight-storage.mjs';
import {createFlightStorageHandler} from '../flight-storage-http.mjs';
const origin='https://release.example.org';
const actor=()=>({authenticated:true,identityMappingReviewed:true,accountId:randomUUID(),wallet:{family:'sui',address:'0x'+'1'.repeat(64)},authOrigin:origin,environment:'release-candidate'});
const snapshot=runId=>({format:'treeforce89.checkpoint.v1',ruleset:'treeforce89.v1',runId,wave:3,score:7713,lives:0,continuesUsed:0,scene:{boss:null,enemies:[]}});
function fixture(){const calls=[];const db={query:async(sql,args)=>{calls.push({sql,args});return{rows:[{result:{stored:true}}]}}};return{calls,store:createFlightStorage(db,{authOrigin:origin,environment:'release-candidate'})};}
test('canonical checkpoint preserves fractional positions with deterministic digest',()=>{const run=randomUUID(),s=snapshot(run);s.scene.player={x:3.25,y:570.5};const a=encodeCheckpoint(run,s),b=encodeCheckpoint(run,Object.fromEntries(Object.entries(s).reverse()));assert.deepEqual(a,b);assert.equal(a.hash.length,64);assert.equal(JSON.parse(a.text).scene.player.x,3.25)});
test('only exhausted flights with zero continues are accepted',()=>{for(const patch of [{lives:1},{continuesUsed:1},{wave:0},{wave:11},{score:-1},{score:Infinity},{score:1.5},{scene:[]},{accountId:randomUUID()}]){const run=randomUUID();assert.throws(()=>encodeCheckpoint(run,{...snapshot(run),...patch}))}});
test('another flight cannot be substituted',()=>{assert.throws(()=>encodeCheckpoint(randomUUID(),snapshot(randomUUID())),/mismatch/)});
test('checkpoint rejects unsupported values and unsafe numeric precision',()=>{for(const value of [undefined,NaN,Infinity,9007199254740992,2n,new Date()]){const run=randomUUID();assert.throws(()=>encodeCheckpoint(run,{...snapshot(run),scene:{bad:value}}))}});
test('checkpoint depth, size and prototype keys are bounded',()=>{let deep={};for(let i=0;i<45;i++)deep={child:deep};for(const scene of [deep,{large:'x'.repeat(262144)},JSON.parse('{"__proto__":{}}')]){const run=randomUUID();assert.throws(()=>encodeCheckpoint(run,{...snapshot(run),scene}))}});
test('unreviewed identities and old preview environment are refused without DB query',()=>{const f=fixture();for(const patch of [{authenticated:false},{identityMappingReviewed:false},{environment:'preview'},{authOrigin:'https://evil.example'},{wallet:{family:'evm',address:'0x1'}}])assert.throws(()=>f.store.register({...actor(),...patch},randomUUID()),/identity/);assert.equal(f.calls.length,0)});
test('DB uses exact bound parameters rather than string-interpolated snapshots',async()=>{const f=fixture(),a=actor(),run=randomUUID(),s=snapshot(run);s.scene.label="x'); DELETE FROM public.anything; --";await f.store.save(a,run,randomUUID(),s);assert.match(f.calls[0].sql,/\$7,\$8/);assert.equal(f.calls[0].args[0],a.accountId);assert.equal(f.calls[0].sql.includes('DELETE'),false);assert.equal(JSON.parse(f.calls[0].args[6]).scene.label,s.scene.label)});
test('corrupted durable snapshot fails integrity before recovery',async()=>{const run=randomUUID(),text=encodeCheckpoint(run,snapshot(run)).text;const store=createFlightStorage({query:async()=>({rows:[{result:{runId:run,snapshotText:text,checkpointHash:'0'.repeat(64)}}]})},{authOrigin:origin,environment:'release-candidate'});await assert.rejects(store.recover(actor(),run),/integrity/)});
test('saved unreviewed checkpoint cannot authorize a purchase or gameplay restoration',async()=>{const run=randomUUID(),enc=encodeCheckpoint(run,snapshot(run)),a=actor();const store=createFlightStorage({query:async()=>({rows:[{result:{runId:run,snapshotText:enc.text,checkpointHash:enc.hash,validation:'unreviewed',restoreAuthorized:true}}]})},{authOrigin:origin,environment:'release-candidate'});assert.equal((await store.recover(a,run)).restoreAuthorized,false);await assert.rejects(store.resolveValidatedFlight(a,run),/validation-required/)});
function httpFixture(){const calls=[];const a=actor();const storage={register:async(...args)=>{calls.push(args);return{registered:true}},save:async(...args)=>{calls.push(args);return{stored:true}},recover:async(...args)=>{calls.push(args);return{restoreAuthorized:false}}};const h=createFlightStorageHandler({storage,resolveSession:async()=>a,allowRequest:async()=>true,origin});return{calls,h,a};}
const req=(body,headers={})=>new Request(origin+'/api/tree-flight',{method:'POST',headers:{Origin:origin,'Content-Type':'application/json',...headers},body:JSON.stringify(body)});
test('handler uses server resolved identity and same-origin request',async()=>{const f=httpFixture();const r=await f.h(req({action:'register',runId:randomUUID()}));assert.equal(r.status,200);assert.equal(f.calls[0][0],f.a);assert.match(r.headers.get('cache-control'),/no-store/)});
test('browser cannot pass account, environment or verification flags',async()=>{const f=httpFixture();for(const patch of [{accountId:randomUUID()},{actor:actor()},{verified:true},{paymentsEnabled:true}])assert.equal((await f.h(req({action:'register',runId:randomUUID(),...patch}))).status,400);assert.equal(f.calls.length,0)});
test('cross-origin requests do not reach storage',async()=>{const f=httpFixture();assert.equal((await f.h(req({action:'recover',runId:randomUUID()},{Origin:'https://evil.example'}))).status,403);assert.equal(f.calls.length,0)});
test('missing session and rate limits are enforced',async()=>{for(const [session,allowed,status] of [[null,true,401],[actor(),false,429]]){const h=createFlightStorageHandler({storage:{},resolveSession:async()=>session,allowRequest:async()=>allowed,origin});assert.equal((await h(req({action:'recover',runId:randomUUID()}))).status,status)}});
test('oversized request rejected without snapshot write',async()=>{const f=httpFixture();assert.equal((await f.h(req({action:'checkpoint',snapshot:'x'.repeat(270000)}))).status,413);assert.equal(f.calls.length,0)});
test('unhandled DB errors never expose SQL, credentials or data',async()=>{const h=createFlightStorageHandler({storage:{register:async()=>{throw Error('password=secret SELECT records')}},resolveSession:async()=>actor(),allowRequest:async()=>true,origin});const r=await h(req({action:'register',runId:randomUUID()}));assert.equal(r.status,503);assert.deepEqual(await r.json(),{error:'flight-storage-unavailable'})});
