import {test} from 'node:test';import assert from 'node:assert/strict';import {createHash,randomUUID} from 'node:crypto';
import {createRecoveryGateway,canonicalSnapshot} from '../recovery-gateway.mjs';
import {accountDeployment,RECOVERY_AUTH_ORIGIN,RECOVERY_GAME_ORIGIN} from '../../../netlify/lib/recovery-candidate-config.mjs';
const token='a'.repeat(64),accountId=randomUUID(),runId=randomUUID();
const snapshot={format:'treeforce89.checkpoint.v1',ruleset:'treeforce89.v1',runId,wave:3,score:12345,lives:0,continuesUsed:0,scene:{codec:'formation-recovery.v1',x:12.125}};
const request=(c,headers={})=>new Request('https://example.invalid/',{method:'POST',headers:{Authorization:'Bearer '+token,'Content-Type':'application/json',...headers},body:JSON.stringify(c)});
function fixture(){let seen=null,calls=0;let who={authenticated:true,environment:'preview',accountId,wallet:{family:'sui',address:'0x'+'1'.repeat(64)},expiresAt:Date.now()+60000};const handler=createRecoveryGateway({verifySession:async t=>{assert.equal(t,token);return who;},invokeStorage:async p=>{calls++;seen=p;return{stored:true,paymentsEnabled:false,restoreAuthorized:false};}});return{handler,get calls(){return calls},get seen(){return seen},change(v){who=v}};}
test('verified session maps storage to server identity and exact canonical hash',async()=>{const f=fixture(),r=await f.handler(request({action:'save',runId,requestId:randomUUID(),snapshot}));assert.equal(r.status,200);assert.equal(f.seen.p_account,accountId);assert.equal(f.seen.p_hash,createHash('sha256').update(f.seen.p_snapshot).digest('hex'));assert.equal(JSON.parse(f.seen.p_snapshot).scene.x,12.125);assert.equal((await r.json()).restoreAuthorized,false)});
for(const extra of [{accountId},{payer:'0x2'},{verified:true},{paymentsEnabled:true},{receiptId:'fake'},{environment:'mainnet'}])test('browser command cannot inject '+Object.keys(extra)[0],async()=>{const f=fixture(),r=await f.handler(request({action:'list',...extra}));assert.equal(r.status,400);assert.equal(f.calls,0)});
for(const headers of [{Authorization:''},{Authorization:'Bearer fake'},{Origin:'https://evil.example'},{'sec-fetch-site':'same-origin'},{'Content-Type':'text/plain'}])test('invalid request boundary '+JSON.stringify(headers),async()=>{const f=fixture(),r=await f.handler(request({action:'list'},headers));assert.ok(r.status>=400);assert.equal(f.calls,0)});
test('expired or EVM identity never touches storage',async()=>{for(const who of [null,{authenticated:true,environment:'preview',accountId,wallet:{family:'evm'},expiresAt:Date.now()+60000}]){const f=fixture();f.change(who);assert.equal((await f.handler(request({action:'list'}))).status,401);assert.equal(f.calls,0)}});
test('non-exhausted flight fails before write',async()=>{const f=fixture();assert.equal((await f.handler(request({action:'save',runId,requestId:randomUUID(),snapshot:{...snapshot,lives:1}}))).status,400);assert.equal(f.calls,0)});
test('canonical JSON rejects prototype keys, deep values and oversized bodies',async()=>{assert.throws(()=>canonicalSnapshot(JSON.parse('{"__proto__":{}}')));let v={};for(let i=0;i<20;i++)v={x:v};assert.throws(()=>canonicalSnapshot(v));const f=fixture();const r=await f.handler(request({action:'list',x:'a'.repeat(280001)}));assert.equal(r.status,413);assert.equal(f.calls,0)});
test('unexpected storage errors are redacted',async()=>{const h=createRecoveryGateway({verifySession:async()=>({authenticated:true,environment:'preview',accountId,wallet:{family:'sui',address:'0x'+'1'.repeat(64)},expiresAt:Date.now()+1000}),invokeStorage:async()=>{throw Error('password secret SQL')}});const r=await h(request({action:'list'}));assert.equal(r.status,503);assert.doesNotMatch(await r.text(),/password|SQL/)});
test('candidate authentication preserves source namespace while changing exact audience',()=>{const values={TREE_ACCOUNT_PREVIEW_ENABLED:'true',TREE_ACCOUNT_PREVIEW_ORIGIN:'https://deploy-preview-18--tree-token.netlify.app',TREE_ACCOUNT_GAME_ORIGIN:'https://deploy-preview-1--treeforce89.netlify.app'},env={get:k=>values[k]};const c=accountDeployment(new Request(RECOVERY_AUTH_ORIGIN),env);assert.equal(c.storedOrigin,values.TREE_ACCOUNT_PREVIEW_ORIGIN);assert.equal(c.gameOrigin,RECOVERY_GAME_ORIGIN);assert.equal(accountDeployment(new Request('https://tree-token.xyz'),env),null);assert.equal(accountDeployment(new Request('https://deploy-preview-999--tree-token.netlify.app'),env),null)});
