import {test} from 'node:test';
import assert from 'node:assert/strict';
import {createRuntimeCheck,inspectConnections,poolSettings,checkRole,MODES,PROJECT,ENV_NAMES} from '../runtime-check/check.mjs';
const token='a'.repeat(64);
const env=Object.fromEntries(MODES.map((m,i)=>[ENV_NAMES[m],`postgresql://tree_continue_${m}_app_v1.${PROJECT}:${String.fromCharCode(65+i).repeat(48)}@aws-0-us-east-2.pooler.supabase.com:6543/postgres`]));
const expected={orders:['commerce_policy_read()','commerce_read(uuid,text,text,text,uuid)','commerce_save_order(uuid,text,text,text,uuid,jsonb,text,jsonb)'],settlement:['commerce_policy_read()','commerce_read(uuid,text,text,text,uuid)','commerce_settle(uuid,text,text,text,uuid,uuid,jsonb)'],storage:['read_recovery(uuid,text,text,text,uuid)','register_flight(uuid,text,text,text,uuid)','store_checkpoint(uuid,text,text,text,uuid,uuid,text,text)'],delivery:['paid_delivery(uuid,text,text,text,uuid,text,text,uuid,uuid,text)'],recovery:['lookup_purchases(uuid,text,text,text,uuid,uuid)','reserve_receipt_scan(uuid,text,text,text,uuid)']};
const row=mode=>({login:`tree_continue_${mode}_app_v1`,effective_user:`tree_continue_${mode}_app_v1`,restricted:true,not_owner:true,restricted_membership:true,direct_tables:false,direct_sequences:false,can_create:false,member_roles:[`tree_continue_${mode}`],functions:expected[mode].map(f=>'tree_continue_v1.'+f)});
const policy={newOrdersEnabled:false,settlementEnabled:false,deployment:null,totalLimitRaw:'0',reservedRaw:'0',environment:'release-candidate',authOrigin:'https://deploy-preview-48--tree-token.netlify.app',adminWallet:'0x485953e2eadf4aa02af950cf8e914fbd2b67523385e73c36118341459d8d45c4',pilotWallet:'0x18d72fc2a3df6d92d0806da3b04d92be056e2d6d35882a56c16ddb25f48d35d6'};
function request(body={action:'check'},extra={}){return new Request('https://example.invalid/check',{method:'POST',headers:{Authorization:'Bearer '+token,'Content-Type':'application/json',...extra},body:typeof body==='string'?body:JSON.stringify(body)});}
function handler(overrides={}){let calls=0;const h=createRuntimeCheck({getEnv:()=>token,inspect:async()=>{calls++;return{credentialsVerified:true,paymentsEnabled:false,restoreAuthorized:false};},...overrides});return{h,calls:()=>calls};}
function pools(mutator=()=>{}){let ended=0,released=0,queries=[];return{get ended(){return ended},get released(){return released},queries,createPool(settings){const mode=settings.user.match(/^tree_continue_(\w+)_app_v1/)[1];assert.equal(settings.ssl.rejectUnauthorized,true);return{end:async()=>{ended++},connect:async()=>({release(){released++},query:async(sql)=>{queries.push(sql);if(sql.includes('AS effective_user')){const r=row(mode);mutator(r,mode);return{rows:[r]};}if(sql.includes('commerce_policy_read() AS result'))return{rows:[{result:policy}]};return{rows:[]};}})}}};}
test('missing setup secret is closed before inspection',async()=>{const f=handler({getEnv:()=>undefined}),r=await f.h(request());assert.equal(r.status,503);assert.equal(f.calls(),0)});
test('unauthenticated and incorrect tokens cannot inspect',async()=>{const f=handler();for(const auth of ['', 'Bearer '+ 'b'.repeat(64),'Bearer not-a-token']){const r=await f.h(request({action:'check'},{Authorization:auth}));assert.equal(r.status,401)}assert.equal(f.calls(),0)});
test('browser-origin requests cannot inspect',async()=>{const f=handler();const r=await f.h(request({action:'check'},{Origin:'https://evil.example'}));assert.equal(r.status,403);assert.equal(f.calls(),0)});
test('GET and non-JSON requests are refused',async()=>{const f=handler();assert.equal((await f.h(new Request('https://example.invalid'))).status,405);assert.equal((await f.h(request({}, {'Content-Type':'text/plain'}))).status,415)});
for(const action of ['order','settle','reconcile','activate_delivery','save','execute'])test('never routes mutation '+action,async()=>{const f=handler();assert.equal((await f.h(request({action}))).status,400);assert.equal(f.calls(),0)});
test('extra fields and malformed body refused',async()=>{for(const body of [{action:'check',enabled:true},'[]','{',JSON.stringify({action:'check',padding:'x'.repeat(800)})]){const f=handler();assert.equal((await f.h(request(body))).status,400);assert.equal(f.calls(),0)}});
test('safe response and no-store headers',async()=>{const f=handler(),r=await f.h(request());assert.equal(r.status,200);assert.match(r.headers.get('cache-control'),/no-store/);assert.equal((await r.json()).paymentsEnabled,false)});
test('raw connection errors are redacted',async()=>{const f=handler({inspect:async()=>{throw Error('postgres://SECRET@HOST')}}),r=await f.h(request()),text=await r.text();assert.equal(r.status,503);assert.ok(!text.includes('SECRET'));assert.ok(!text.includes('HOST'))});
test('same isolate rate limit avoids repeated connection storms',async()=>{const f=handler({now:()=>100});assert.equal((await f.h(request())).status,200);assert.equal((await f.h(request())).status,429);assert.equal(f.calls(),1)});
test('all five URL configurations require encrypted verified TLS',()=>{for(const mode of MODES){const c=poolSettings(env[ENV_NAMES[mode]],mode);assert.equal(c.ssl.rejectUnauthorized,true);assert.equal(c.max,1)}});
for(const [name,change] of [['foreign host',u=>u.replace('.pooler.supabase.com','.evil.example')],['owner login',u=>u.replace('tree_continue_orders_app_v1','postgres')],['another project',u=>u.replace(PROJECT,'x'.repeat(20))],['unsafe ssl option',u=>u+'?sslmode=disable'],['fragment',u=>u+'#x'],['session port',u=>u.replace(':6543',':5432')],['short password',u=>u.replace('A'.repeat(48),'abc')]])test('URL rejects '+name,()=>assert.throws(()=>poolSettings(change(env[ENV_NAMES.orders]),'orders'),/configuration/));
test('five distinct connections verify expected function grants',async()=>{const f=pools(),r=await inspectConnections({getEnv:k=>env[k],createPool:f.createPool});assert.equal(r.credentialsVerified,true);assert.deepEqual(r.checkedRoles,MODES);assert.equal(r.policyDisabled,true);assert.equal(f.ended,5);assert.equal(f.released,5);assert.ok(f.queries.every(q=>/^(SELECT|BEGIN READ ONLY|SET LOCAL|COMMIT|ROLLBACK)/.test(q)))});
for(const field of ['restricted','not_owner','restricted_membership'])test('role rejects false '+field,()=>assert.throws(()=>checkRole({...row('orders'),[field]:false},'orders'),/role-verification/));
for(const field of ['direct_tables','direct_sequences','can_create'])test('role rejects dangerous '+field,()=>assert.throws(()=>checkRole({...row('orders'),[field]:true},'orders'),/role-verification/));
test('overlapping memberships and changed function authority rejected',()=>{assert.throws(()=>checkRole({...row('orders'),member_roles:['tree_continue_orders','tree_continue_settlement']},'orders'));assert.throws(()=>checkRole({...row('orders'),functions:[...row('orders').functions,'tree_continue_v1.paid_delivery()']},'orders'))});
test('a bad role closes its connection and never checks the next role',async()=>{const f=pools(r=>r.direct_tables=true);await assert.rejects(inspectConnections({getEnv:k=>env[k],createPool:f.createPool}),/role-verification/);assert.equal(f.ended,1);assert.equal(f.released,1);assert.ok(f.queries.includes('ROLLBACK'))});
test('missing credential and duplicate passwords fail before network',async()=>{let calls=0;await assert.rejects(inspectConnections({getEnv:()=>undefined,createPool:()=>{calls++}}));const copy={...env,[ENV_NAMES.settlement]:env[ENV_NAMES.settlement].replace('B'.repeat(48),'A'.repeat(48))};await assert.rejects(inspectConnections({getEnv:k=>copy[k],createPool:()=>{calls++}}));assert.equal(calls,0)});
